### ISSUE TITLE
Make Nav Menu items active for active section

### ISSUE THREAD

**Issue by vishalsanghai** [vishalsanghai/trackyo#1]
Visit http://beta.trackyotech.com/
The navigation menu buttons state should change to active when the corresponding section is being viewed. For example if the user if viewing the blog section the blog menu button should have a class active.
P.S. : Not all sections have a menu button, and I intend to keep it this way.

**Comment by prabushitha** [comment]
Hi, I can work on this issue

**Comment by vishalsanghai** [comment]
Hi, @prabushitha would love your help in this!
I am assigning you on this. You can start working and then send a pull request.

**Comment by prabushitha** [comment]
@vishalsanghai added a pull request #4
