### ISSUE TITLE
Animate the css circle in "What people feel about Trackyo" part.

### ISSUE THREAD

**Issue by vishalsanghai** [vishalsanghai/trackyo#2]
While loading "What people feel about Trackyo" section the circle-border, which denotes percentage should get filled with animation.

**Comment by GingerDragon7** [comment]
hello @vishalsanghai ...i want to work on this..!!

**Comment by vishalsanghai** [comment]
Hi, @GingerDragon7 would love your help in this!
I am assigning you on this. You can start working and then send a pull request.

**Comment by GingerDragon7** [comment]
hey @vishalsanghai ....is there any faq's channel.....i mean to deploy this locally ....fork it....clone it....npm i ....gulp ?

**Comment by vishalsanghai** [comment]
@GingerDragon7 sorry there is no faq or starter guide for now.
You can fork it, clone it and you are good to go. No need for npm or gulp all dependencies are connected via CDN, so no compilation whatsoever.

**Comment by GingerDragon7** [comment]
@vishalsanghai ....alright....thanks a lot.....i am seeing it!!!!
