### ISSUE TITLE
Videos should play on scroll instead of onhover

### ISSUE THREAD

**Issue by vishalsanghai** [vishalsanghai/trackyo#3]
The 4 videos embedded in How it works section, currently plays when hovered over. Instead it should play automatically when it is visible on the screen on scrolling.

**Comment by elias-garcia** [comment]
I can work on this 😃

**Comment by vishalsanghai** [comment]
Hi, @elias-garcia  would love your help in this!
I am assigning you on this. You can start working and then send a pull request.

**Comment by vishalsanghai** [comment]
Hey do you need any help?
You can go to beta.trackyotech.com for live demo of the project.

**Comment by elias-garcia** [comment]
I've cloned the repo and I'm having a look on the code by the moment. Do you want to play the video when it's shown on the screen and pause it when it hides? For example, if you have two videos at the sime time on the screen you want to play the 2 at the same time?

**Comment by vishalsanghai** [comment]
Yes.
The video container takes 80% of the screen, so at a time 80% of the screen would be taken by a video and 20% by the video below it. So yes the video taking the most space in screen should be playing. It should play the video whose atleast 50% is on screen.

**Comment by elias-garcia** [comment]
Ok, I'll try to do that.
